[package]
name = "hyperlocal"
version = "0.2.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Hyper bindings for unix domain sockets"
homepage = "https://github.com/softprops/hyperlocal"
repository = "https://github.com/softprops/hyperlocal"
keywords = ["hyper", "unix", "sockets", "http"]
license = "MIT"

[features]
default = ["external_unix_socket"]
external_unix_socket = ["unix_socket"]

[dependencies]
hyper = "0.9"
rustc-serialize = "0.3"
unix_socket = { version = "0.5", optional = true}
url = "1.0"
